language: scala
jdk:
- oraclejdk8
scala:
- 2.11.12
script:
- cd code
- sbt --info ++$TRAVIS_SCALA_VERSION +publishLocal
- cd ../test-app
- sbt --info ++$TRAVIS_SCALA_VERSION -DplayTestVersion=2.6.0 +test
- sbt --info ++$TRAVIS_SCALA_VERSION -DplayTestVersion=2.6.1 +test
- sbt --info ++$TRAVIS_SCALA_VERSION -DplayTestVersion=2.6.2 +test
- cd ../test-app-filters
- sbt --info ++$TRAVIS_SCALA_VERSION -DplayTestVersion=2.6.0 +test
- sbt --info ++$TRAVIS_SCALA_VERSION -DplayTestVersion=2.6.1 +test
- sbt --info ++$TRAVIS_SCALA_VERSION -DplayTestVersion=2.6.2 +test
- cd ../code
after_success:
- ! '[[ $TRAVIS_BRANCH == "master" ]] && { sbt --info +publish; };'
- python <(curl -s https://raw.githubusercontent.com/TouK/sputnik-ci/master/sputnik-ci.py)
sudo: false
